name: Make

on:
  push:
    branches:
      - main

  # Run tests for any PRs.
  pull_request:

jobs:
  # Run tests.
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Pull required images
        run: |
          docker compose pull

      - name: Run build
        run: |
          docker compose build

      - name: Run test
        run: |
          docker compose run builder

  deploy:
    needs: test

    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - uses: actions/checkout@v4

      - name: Login to GitHub Packages
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}

      - name: Pull required images
        run: |
          docker compose pull

      - name: Run build
        run: |
          docker compose build

      - name: Run test
        run: |
          docker compose run builder

      - name: Make public
        run: |
            cp main.pdf public/

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: gh-pages
